# Generated by Django 6.0.3 on 2026-04-02 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='is_admin',
        # ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid username', regex='^[A-Za-z][A-Za-z0-9]{3,19}$')]),
        ),
    ]
