# Generated by Django 6.0.3 on 2026-03-25 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
