# Generated by Django 6.0.3 on 2026-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
